name: Free space on GH runner
on: workflow_dispatch
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    
    - name: Before
      run: |
        set -xe
        df -H

    - name: Removing stuff
      run: |
        set -xe
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/share/swift
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/.ghcup
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo rm -rf /opt/hostedtoolcache/
        sudo rm -rf /usr/local/graalvm/
        sudo rm -rf /usr/local/share/powershell
        sudo rm -rf /usr/local/share/chromium
        sudo rm -rf /usr/local/lib/node_modules
        sudo docker image prune --all --force
        
        APT_PARAMS='sudo apt -y -qq -o=Dpkg::Use-Pty=0'
        $APT_PARAMS remove -y '^dotnet-.*'
        $APT_PARAMS remove -y '^llvm-.*'
        $APT_PARAMS remove -y '^php.*'
        $APT_PARAMS remove -y '^mongodb-.*'
        $APT_PARAMS remove -y '^mysql-.*'
        $APT_PARAMS remove -y azure-cli google-* google-chrome-stable firefox powershell mono-devel libgl1-mesa-dri
        $APT_PARAMS autoremove --purge -y
        $APT_PARAMS autoclean
        $APT_PARAMS clean

    - name: After
      run: |
        set -xe
        df -H
